export const ADD_HAMSTERS = 'ADD_HAMSTERS';
export const HAMSTERS_LOADING = 'HAMSTERS_LOADING';
export const HAMSTERS_FAILED = 'HAMSTERS_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const ADD_SPECIES = 'ADD_SPECIES';
export const SPECIES_LOADING = 'SPECIES_LOADING';
export const SPECIES_FAILED = 'SPECIES_FAILED';
