export const ADD_HAMSTERS = 'ADD_HAMSTERS';
export const HAMSTERS_LOADING = 'HAMSTERS_LOADING';
export const HAMSTERS_FAILED = 'HAMSTERS_FAILED';

export const ADD_SPECIES = 'ADD_SPECIES';
export const SPECIES_LOADING = 'SPECIES_LOADING';
export const SPECIES_FAILED = 'SPECIES_FAILED';
